:concurrency: 12
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 12 

production:
  :concurrency: 12

:queues:
  -  [general_queue, 1]
  -  [import_queue, 1]
  -  [payment_queue, 1]
  -  [default, 1]

:limits:
  general_queue: 3
  import_queue: 3
  payment_queue: 3
  default: 3
