:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  -  [general_queue, 1]
  -  [import_queue, 1]
  -  [message_queue, 20]
  -  [payment_queue, 1]
  -  [default, 1]
