:concurrency: 25
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5
integration:
  :concurrency: 35 

production:
  :concurrency: 35
:queues:
  -  [general_queue, 1]
  -  [import_queue, 1]
  -  [message_queue, 1]
  -  [payment_queue, 1]
  -  [default, 1]
