defaults:
  sudo_auth_password: '9p5yn123'
  resque_auth_password: '9p5yn123'
  cache_auth_username: 'optyn'
  cache_auth_password: '9p5yn123'
  app_host: 'www.optyn.com'
  api_welcome_message: 'Optyn to receive cool offers, new product announcements, giveaways and other cool announcements.'
  app_base_url: 'https://www.optyn.com'
  app_base_url_http: 'http://www.optyn.com'
  email_app_base_url: 'http://www.simple-send.com'
  bucket: 'optynproduction'
  deployment_shared_path: <%= "#{Rails.root}/tmp/" %>
  dashboard_limit: 5
  ttls:
    message_folder: <%= 24.hours %>
    dashboard_count: <%= 1.minutes %>
    email_footer: <%= 1.hour %>
  twitter_consumer_key: 'vJiyJWYJZ12Tstri6mixCA'
  twitter_consumer_secret: 'VXn4l4p84wVSp6RK6n2NAIpkBfTAxJOHemjvAiAzU'
  facebook_app_key: '585087778190652'
  facebook_app_secret: '01b7451dffc56a99a02dee21fa0a2e1c'
  google_client_id: '951432870594-tgl40gk38gsg55cmvgpm3gsb5mvovbfl.apps.googleusercontent.com'
  google_client_secret: '2wbPrU70K8Je6LTQyRzSIhQ4'
  linkedin_api_key: 'r5c0m0cjxhr1'
  linkedin_secret_key: 'A9t9kMCWlkQKjHVj'
  aws_access_key_id: 'AKIAJO7WB66NE2EDUV2Q'
  aws_secret_access_key: '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'
  #Add the welcome message for the optyn button
  #Add Bucket name for s3
  optyn_partner_redirect_uri: 'https://partners.optyn.com/partners/auth/optyn/callback'
  robots_redirect_uri: 'https://www.optyn.com/robots.txt'
  eatstreet_curation_email: 'office@eatstreet.com'
  #Also used in Optyn Tracking
  template_encryption_secret: "9p5yn1231391000158" 
  app_reseller_url: 'http://localhost:3002'
  reseller_edit_location: 'message_actions/:placeholder/edit'
  reseller_reject_location: 'message_actions/:placeholder/reject'
  reseller_approve_location: 'message_actions/:placeholder/approve'
  send_grid_username: 'ggaglani-services'
  send_grid_password: '9p5yn123'

  #trackings
  track_app_base_url: 'http://simple-send.com'
  simple_delivery:
    open_path: '/emails/o'
    link_path: '/emails/l'
    unsubscribe_path: '/emails/unsubscribe'
    qr_code_path: '/emails/g'
    offer_relevant: '/emails/relevant'
    segments_prefix: '/emails/segments'
    segments_default: '/default'
    tiny_url_path: '/s'

staging:
  twitter_consumer_key: 'PIlc0WbUl3KOK11yQG9DQ'
  twitter_consumer_secret: 'bTGpU2SLyqai4yGbMzqfrTP20zxbNYySroKd9HIxeM'
  facebook_app_key: '624632634229184'
  facebook_app_secret: 'f1675b7e3b2027d69b14e8421e80ebaa'
  google_client_id: '951432870594-kfenjdp27bk83bb5r9vm55rielr30i4h.apps.googleusercontent.com'
  google_client_secret: 'Nb-tX1RofqWfyiSsh3GNt8Wn'
  linkedin_api_key: 'j90jf1gvh8t7'
  linkedin_secret_key: 'fHPWIwhGCnVr2Iue'
  app_host: "development.optyn.com"
  stripe_api_key: "sk_test_MFfsB7FXICD2lbEtFWguHZBZ"
  stripe_public_key: "pk_test_cD7RxbHwUlWVDlvfvS3TyCRB"
  app_base_url: 'https://development.optyn.com'
  app_base_url_http: 'http://development.optyn.com'
  email_app_base_url: 'http://development.simple-send.com'
  bucket: 'optynstaging'
  optyn_partner_redirect_uri: 'https://partners-staging.optyn.com/partners/auth/optyn/callback'
  robots_redirect_uri: 'https://development.optyn.com/robots.txt'
  eatstreet_curation_email: 'ian@eatstreet.com'
  app_reseller_url: "https://reseller-staging.optyn.com"
  track_app_base_url: 'http://development.simple-send.com'

development:  
  twitter_consumer_key: 'Acwx2jBkCCbFZHkW8wEubQ'
  twitter_consumer_secret: 'zGevh2gWCvuW2h2BXPe84arg5sm7A4bEWmxvHddno'
  facebook_app_key: '427608267320854'
  facebook_app_secret: 'f2dd8beb43c9c952d5b45a31534e56ba'
  google_client_id: '951432870594.apps.googleusercontent.com'
  google_client_secret: 'sR-X_aq5jf3QGNvBkZlPIADz'
  linkedin_api_key: 'f5thzgptqhu8'
  linkedin_secret_key: '6ZZACokbw3IJfwRN'
  app_host: "localhost:3000"
  stripe_api_key: "sk_test_4BJp7qosDLIvEocBeWMgxhI9"
  stripe_public_key: "pk_test_OvjvjiEuAFjvonAaaNAbh9XT"
  app_base_url: 'http://localhost:3000'
  app_base_url_http: 'http://localhost:3000'
  email_app_base_url: 'http://localhost:3001'
  bucket: 'optyndevelopment'
  optyn_partner_redirect_uri: 'http://localhost:3001/partners/auth/optyn/callback'
  robots_redirect_uri: 'http://localhost:3000/robots.txt'
  app_reseller_url: "http://localhost:3002"

production:
  #change in the live mode
  stripe_api_key: "sk_live_aGKZExHv7US4OrRF1bqf578d"
  stripe_public_key: "pk_live_xYqRLdkAEE3V4qVijQfpuuOK"
  app_reseller_url: 'https://reseller.optyn.com'

integration:
  twitter_consumer_key: 'PIlc0WbUl3KOK11yQG9DQ'
  twitter_consumer_secret: 'bTGpU2SLyqai4yGbMzqfrTP20zxbNYySroKd9HIxeM'
  facebook_app_key: '624632634229184'
  facebook_app_secret: 'f1675b7e3b2027d69b14e8421e80ebaa'
  google_client_id: '951432870594-kfenjdp27bk83bb5r9vm55rielr30i4h.apps.googleusercontent.com'
  google_client_secret: 'Nb-tX1RofqWfyiSsh3GNt8Wn'
  linkedin_api_key: 'j90jf1gvh8t7'
  linkedin_secret_key: 'fHPWIwhGCnVr2Iue'
  app_host: "development.optyn.com"
  stripe_api_key: "sk_test_MFfsB7FXICD2lbEtFWguHZBZ"
  stripe_public_key: "pk_test_cD7RxbHwUlWVDlvfvS3TyCRB"
  app_base_url: 'https://development.optyn.com'
  app_base_url_http: 'http://development.optyn.com'
  email_app_base_url: 'https://integration.simple-send.com'
  bucket: 'optynstaging'
  optyn_partner_redirect_uri: 'https://partners-staging.optyn.com/partners/auth/optyn/callback'
  robots_redirect_uri: 'https://development.optyn.com/robots.txt'
  eatstreet_curation_email: 'ian@eatstreet.com'
