defaults:
  template_engine_username: 'admin'
  template_engine_password: 'test123'
  resque_auth_password: '9p5yn123'
  app_host: 'optyn.com'

  #Add the twitter consumer key and twitter consumer secret
  #Add the facebook app key and facebook app secret
  #Add the google client key and google client secret
  #Add the linkedin app id and linkedin client secret   
  #Add the app_base_url

development:  
  twitter_consumer_key: 'Acwx2jBkCCbFZHkW8wEubQ'
  twitter_consumer_secret: 'zGevh2gWCvuW2h2BXPe84arg5sm7A4bEWmxvHddno'
  facebook_app_key: '427608267320854'
  facebook_app_secret: 'f2dd8beb43c9c952d5b45a31534e56ba'
  google_client_id: '951432870594.apps.googleusercontent.com'
  google_client_secret: 'sR-X_aq5jf3QGNvBkZlPIADz'
  linkedin_api_key: 'f5thzgptqhu8'
  linkedin_secret_key: '6ZZACokbw3IJfwRN'
  app_host: "localhost:3000"
  stripe_api_key: "sk_test_LvqRzhN1kzeKaqQRPsQ9Vug0"
  stripe_public_key: "pk_test_JpL5IkK8MiKjycqdYsfAQO1c"
  app_base_url: 'http://localhost:3000'

  