defaults:
  template_engine_username: 'admin'
  template_engine_password: 'test123'
  #Add the twitter consumer key and twitter consumer secret
  #Add the facebook app key and facebook app secret
  #Add the google client key and google client secret

development:
  twitter_consumer_key: pjUQYrlYCkPhCVgcCCLMIQ
  twitter_consumer_secret: WOdUR2aeqS5fUuQ0yG1wzu8jkg7EtwkamZMvNJg
  facebook_app_key: '640917622601161'
  facebook_app_secret: 'b62d17627f5e3be802e007792d7fafef'
  google_client_id: '951432870594.apps.googleusercontent.com'
  google_client_secret: 'sR-X_aq5jf3QGNvBkZlPIADz'