1:
  min: 101
  max: 250
  amount: 5
  name: '5pm'

2:
  min: 251
  max: 500
  amount: 10
  name: '10pm'

3:
  min: 501
  max: 1000
  amount: 15
  name: '15pm'

4:
  min: 1001
  max: 2500
  amount: 20
  name: '20pm'

5:
  min: 2501
  max: 5000
  amount: 25
  name: '25pm'